# Generated by Django 4.2 on 2023-04-20 15:32

from django.db import migrations, models
import django.db.models.deletion
import myweb.api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
                ('serial_number_mask', models.CharField(max_length=255, validators=[myweb.api.validators.validator_serial_number_mask])),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('comment', models.CharField(default='', max_length=255)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.equipment_type')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique serial'),
        ),
    ]
