# Generated by Django 4.2 on 2023-04-24 14:02

from django.db import migrations, models
import django.db.models.deletion
import myweb.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.equipment_type', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='serial_number_mask',
            field=models.CharField(max_length=255, validators=[myweb.api.validators.validator_serial_number_mask], verbose_name='Маска SN'),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='type_name',
            field=models.CharField(max_length=255, verbose_name='Тип оборудования'),
        ),
    ]
