# Generated by Django 4.2 on 2023-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_equipment_id_alter_equipment_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='SN'),
        ),
    ]
